# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('count', models.IntegerField()),
                ('ctime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
