# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_auto_20180619_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsearch',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
