# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0004_auto_20180619_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostsearch',
            old_name='content',
            new_name='name',
        ),
    ]
